version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      TKIyYGFuX8Lre0KZ7Yff0gUsVorBGE2uZU1+b0x6rqDB7yDn83V0Umcx99yoqxmByVPkTK5dqwkINcD0o0aJxBO1e0eGN5k+Lh2ajyewVOgpwLm7uC4tiA3EEiQaTZ8KHLfKdYtn9lfD+u7TV9mble5qMM1VMEFmbPcK3avh2Cru/+KEtv/n+3fVsigZupMZI9rxg6VeuQuULhghqh5OqkevLYaZR4ArGajdHZ0jLTrcPQgnH8FdqFOhHV44bdavrw0PlEzxZnG5F4zgNxWztpnf1i7MXLsOozIa+TfIAUO5mCcx0OW+46hNlb9k67TdJIZZe/UOqn6bF5AAmWl5OXWoB56tFt9KsHQ3QKiw+av8SzmJSUclG4kgspXdyjA8X1jZDZ0HEEKSgexPCG5vinB0ZS2w2PxxCyZZWs9c9znSAs2JJUmu8+Wq1MMrgQOiWr/XzxBxl/Aln4NTXTqqZjSFQ0nwDoUoAyUDPvVbmshoE7hAmGhF5W3GU8MKq5bCixazSbuee3qgILKIhYreChUbP5rpqMcXvsksiOXnjdUOw7k0Cu1efP82rfWVucJNRzjDkewRMe7l4rpIT7VZ69Xp+H/ywWmmJ/P0Vix00sUwJiHl0vq9wCWoKPb/ew55bbT3JKKTV7RNfThnhFzM0/AOzvrAQC4XUd2heir6C7w=
