version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      rFCE1tqtBghYpaS1TBR0sp3wg/jvSYojKsghKE8LiSud6/+dH5poM7OqZIAEyDZzIQ6zrRYhw7HiT2Xm9YC6qMqMa9D6pkVn5f44bTjbet+nY6BbIET2+KMt3g9/IsAV5f1XdVc1et+En28qc7TyaNuZqKn7VG1YrBJxujSB5Sr34fshCj8NNe6qeWjz5fM1rFwhCPIKBxGhexMYJvkLtyX6CxoJCWSqjlDsvhGJM8A2Yd+Rp73K+LqVsAab+4Ida2nxjRlHp4WFigLxXvl+khPwHwIHMXblrFw4YFlM0T5ErPBoELTJupuis1VrRQeb7p7e93Ql3UPNxkcE5jkEbBMx891TDN7fz623c1ONTaSgk8XPdYJLnFziRId8IJ7D9QL/+yLA7s0QLKaonm+ex6Yhh4y5/n21UzfYvzs/02j7BYs9mK4DM50aex0RPsXhhTflP4kHg9sQRABh2VYkdVRmhH5KnA1am2zpxsp/pggP6jHIYqbJqCQck0U7+F1qiK1+V0GLt1AbumWFDa4wzLVU1Lrob/Ee3lYeS0ZH1mmjXvN2ycI0pPbsvGQ6D56Tu1NtvvjJ/lZdVpc6WV1EMhE+++ZdSjZ0amxAKjR8imVsuDryMf4Va9W1RZREUe7iTiMLBvdG4rk+RTZaGnmk6UYyIvlgOJYKWAMAckRu2dw=
