version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      wyS8IoaThz9WaXnr2HFgJN1tVHi9utA7oXAKQ170YbIqK5Gp3K/yLvQjssmxaMLdW5gzMBzYruSntOmyH8nU9W2yhyMFHG3bl2zZHPJRqp/XSoYZxUzdpbiI+BnB08a/VFdRG7c6Xu0ij+Fwt+qNlyDTugE+1hgoMCH2Qb0svIAL7Iq5jqXtIuVFrEUrXENGsIx7l8GWUFfqWkg/OZKUSfEL0OekYcYLpxiQMZ2VwD3trc20xL9mkeb5PJUuTK+L10Z7qfFlYxotp9miPDG8FFUYPuZy/u3v4IRajmUsd2Qxduy/vyA4SRd3nI5P3+rMINHMffpHK+nM/tQya2VTD0fr3ZX21eWeReomw5DMYYO5BD2+E/hvnIpvePrHFmA+M+UHYLs81VbFntNf4D7PaesNZqSA0A3/LWhSyQHcFGWKcjHCaNdBCBfxqAZZl7c65LThfqegOLWK/oPvFl1b/fgwXH7e2gSmKCVPIWTAn9bv9NfohA/taKEKzz7oo1XK/JQMNAvkeA7s8Voq+0Gr82iQJvO3PlYUUk4clIiJNXz2/PLPZLAMhuNDUzp7zYM+yf6nQ/sjRJTKoHfKYVXo+Vlzhbdf6rwKm1AJRXwbGyyUW0r5GWvbeGd62ins1sfDhjoMozXW8VuD4sE3Q4owZ6hPLezRRkydtRAkEzZ7CGg=
