version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      lftnscl+WNbUw0OdF8GqSwy7zYlz0uuE2bPpoJ6X6dl8drWUGMDsOprnIcU5BfVb9hln8yI68GQMxffjwOcljbCqCkMAueSOFcYl4FNsDwSOeOomkDjLX+ISGhYFAfNnpvabYfrJfkf2rjfVIQSHp/BJ3xMk9X7Hjnx98GUE2WVk5jD3hDGnEtPFC6SYlS5liMmvd8YKeBne0TGkFupmEp5FsRoKVGu8N7OMMj758kQN39HVkLqfCi9HylBvgOx+xyazvcB8p75N0+TXdxStHmlYmmRZyY4FmtyQu2+oYI3r+YtI8IQvIBF26XptJBZIKNu5EqzhfWLcYPKkfP3/cP5gPXReIkf7y3tIu0SgLUpGb68KK04fUl6BCWwQloHw8yrHjv5bnHvXq4XIYveUj3ejl9KnM9Fud8d4R87D+F03zdFqnuz2s4bAoxgCIaAvEb8u++Xt9A/YdZpR2b2zkGSJXGhzxYjNzZ6WDKaLytHifjQC2fXa6HkDKiXWvL1iSFDV1MHbisbj3pcn7fhoT/L6/XUgJsyRqgc7AXoKjvEJ8ClsU3x0pRX5iWEYMTg2xsj7RUJFi6xJP1FqMRcmDb0KB3YnYNsnhKdS43MBfDogYZKg1KTFluB17VpeRvCn7lPxQMHtbRZTxq2AqdZrVWRkjBCRdOLhwuvDaRdcddw=
