version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      O8aLFpZwAoy9bqrAgchoRqG9fwi71H6/dwfzzdo3fnhB+zAHYcZpdozUhXKHz/Vlz5XBozJCtgheyw7YUqJi6rSz5iFpx1jh1XDCMuu3Efwqams86aU2Wxq7ryEqMLfuUcUnybhrmiNNIExJz09iyC2vinmo83JGpVjpBgOiiPYdC3guwOl8sPsDP5n4b33oG4E3K5lmlv6zpEz7I7Hj67b3fWTLF4pXkbO3HtKYVy2hQaxnVu+KmoNdjeTLSWrPL58JdByJvCrV7AfrdBy1woIM3D86TWb/MsHRvQOFl7dGO+IEiXSxTSq233RNZWmTIA74yJ3sd+yUtD1TMTSozHmkaxyMqmmjATWysM12MYm/2DD/Jy1yYsrsLYfA0SBYjFOr+kc4/sYLyeXKNoGNIx/cGhars+MtEYr3CeITk0mTI7xFaTlSK1HBpf7inffaT9IEpwF6YDVzAU7QZGhxJaOvqqxrIzykaN3wlJ3dx1q8ZMeTKCvZLGdnlqad3V10EidO0chy4dMv1pfPx2JnjezIZqbazT2VsLNBlILDk+ROX65mdCCmK3QYMr3tz4lSMT/6cAaAthXLmP31+sm5bmNGFKcXh86UJLatd8C0zjj0wEqXxw/uhgDiqcroav39/GV0fggxoXIggfjruGmBkBScQz3ItW4OEcmc6H4oIdA=
